server:
  port: 11111
spring:
  application:
    name: pearl-code-generator
  datasource:
    url: jdbc:mysql://3306/pearl_generator?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
  freemarker:
    suffix: .ftl
    cache: false
  thymeleaf:
    enabled: true
  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/
